export const apiCatalog = {
  auth: [
    {
      name: "Account",
      description: "Core authentication service (email/password + Google SSO).",
      endpoints: [
        {
          key: "auth-register",
          label: "Register",
          method: "POST",
          path: "/register",
          bodyTemplate: {
            firstName: "Aya",
            lastName: "Benali",
            email: "aya@example.com",
            password: "Secret123!",
            confirmPassword: "Secret123!",
          },
        },
        {
          key: "auth-login",
          label: "Login",
          method: "POST",
          path: "/login",
          bodyTemplate: {
            email: "aya@example.com",
            password: "Secret123!",
          },
        },
        {
          key: "auth-validate",
          label: "Validate Email Token",
          method: "POST",
          path: "/validate",
          bodyTemplate: { token: "<email_token>" },
        },
        {
          key: "auth-reset-request",
          label: "Send Password Reset Email",
          method: "POST",
          path: "/message/reset",
          bodyTemplate: { email: "aya@example.com" },
        },
        {
          key: "auth-reset",
          label: "Reset Password",
          method: "POST",
          path: "/reset",
          bodyTemplate: {
            token: "<reset_token>",
            password: "NewSecret123!",
            confirmPassword: "NewSecret123!",
          },
        },
        {
          key: "auth-profile",
          label: "Profile",
          method: "GET",
          path: "/profile",
          requiresAuth: true,
        },
      ],
    },
  ],
  darna: [
    {
      name: "Auth",
      description: "User lifecycle for the Darna backend.",
      endpoints: [
        {
          key: "darna-register",
          label: "Register",
          method: "POST",
          path: "/auth/register",
          bodyTemplate: {
            firstName: "Aya",
            lastName: "Benali",
            email: "aya@example.com",
            password: "Secret123!",
          },
        },
        {
          key: "darna-login",
          label: "Login",
          method: "POST",
          path: "/auth/login",
          bodyTemplate: {
            email: "aya@example.com",
            password: "Secret123!",
          },
        },
        {
          key: "darna-profile",
          label: "Profile",
          method: "GET",
          path: "/auth/profile",
          requiresAuth: true,
        },
      ],
    },
    {
      name: "Properties",
      description: "CRUD for real-estate listings.",
      endpoints: [
        {
          key: "darna-properties-list",
          label: "List Properties",
          method: "GET",
          path: "/properties",
        },
        {
          key: "darna-properties-create",
          label: "Create Property",
          method: "POST",
          path: "/properties",
          requiresAuth: true,
          bodyTemplate: {
            title: "Luxury duplex",
            description: "Panoramic ocean view",
            price: 2500000,
            currency: "MAD",
            city: "Casablanca",
            media: ["https://picsum.photos/600/400"],
          },
        },
        {
          key: "darna-properties-detail",
          label: "Get Property",
          method: "GET",
          path: "/properties/:id",
          pathParams: ["id"],
        },
        {
          key: "darna-properties-update",
          label: "Update Property",
          method: "PUT",
          path: "/properties/:id",
          requiresAuth: true,
          pathParams: ["id"],
          bodyTemplate: {
            title: "Updated title",
            price: 2100000,
          },
        },
        {
          key: "darna-properties-delete",
          label: "Delete Property",
          method: "DELETE",
          path: "/properties/:id",
          requiresAuth: true,
          pathParams: ["id"],
        },
      ],
    },
    {
      name: "Groups",
      description: "Manage Daret groups.",
      endpoints: [
        {
          key: "darna-groups-list",
          label: "List Groups",
          method: "GET",
          path: "/groups",
          requiresAuth: true,
        },
        {
          key: "darna-groups-create",
          label: "Create Group",
          method: "POST",
          path: "/groups",
          requiresAuth: true,
          bodyTemplate: {
            name: "Casa Daret",
            amount: 5000,
            frequency: "monthly",
          },
        },
        {
          key: "darna-groups-detail",
          label: "Get Group",
          method: "GET",
          path: "/groups/:groupId",
          requiresAuth: true,
          pathParams: ["groupId"],
        },
        {
          key: "darna-groups-join",
          label: "Join Group",
          method: "POST",
          path: "/groups/:groupId/join",
          requiresAuth: true,
          pathParams: ["groupId"],
        },
        {
          key: "darna-groups-contribute",
          label: "Contribute",
          method: "POST",
          path: "/groups/:groupId/contribute",
          requiresAuth: true,
          pathParams: ["groupId"],
        },
      ],
    },
    {
      name: "Chat & Notifications",
      description: "Realtime helpers.",
      endpoints: [
        {
          key: "darna-chat-room",
          label: "Room Messages",
          method: "GET",
          path: "/chat/:roomId/messages",
          requiresAuth: true,
          pathParams: ["roomId"],
        },
        {
          key: "darna-notifications-list",
          label: "List Notifications",
          method: "GET",
          path: "/notifications",
          requiresAuth: true,
        },
        {
          key: "darna-notifications-read",
          label: "Mark Notification Read",
          method: "PATCH",
          path: "/notifications/:id/read",
          requiresAuth: true,
          pathParams: ["id"],
        },
      ],
    },
    {
      name: "Search",
      description: "Discovery endpoints.",
      endpoints: [
        {
          key: "darna-search-properties",
          label: "Search Properties",
          method: "GET",
          path: "/search/properties",
          queryParams: ["city", "minPrice", "maxPrice", "q"],
        },
      ],
    },
  ],
  tirelire: [
    {
      name: "Auth",
      description: "User lifecycle for Tirelire.",
      endpoints: [
        {
          key: "tirelire-register",
          label: "Register",
          method: "POST",
          path: "/auth/register",
          bodyTemplate: {
            name: "Aya Benali",
            email: "aya@example.com",
            password: "Secret123!",
          },
        },
        {
          key: "tirelire-login",
          label: "Login",
          method: "POST",
          path: "/auth/login",
          bodyTemplate: {
            email: "aya@example.com",
            password: "Secret123!",
          },
        },
      ],
    },
    {
      name: "Users",
      description: "Public user directory.",
      endpoints: [
        {
          key: "tirelire-users-list",
          label: "List Users",
          method: "GET",
          path: "/users",
        },
        {
          key: "tirelire-users-create",
          label: "Create User",
          method: "POST",
          path: "/users",
          bodyTemplate: {
            name: "New User",
            email: "new@example.com",
            password: "Secret123!",
          },
        },
      ],
    },
    {
      name: "Groups & Contributions",
      description: "Savings groups and payments.",
      endpoints: [
        {
          key: "tirelire-groups-create",
          label: "Create Group",
          method: "POST",
          path: "/groups",
          requiresAuth: true,
          bodyTemplate: {
            name: "Casa Premium",
            amount: 3000,
            frequency: "monthly",
            capacity: 12,
          },
        },
        {
          key: "tirelire-groups-list",
          label: "List Groups",
          method: "GET",
          path: "/groups",
          requiresAuth: true,
        },
        {
          key: "tirelire-groups-detail",
          label: "Group Details",
          method: "GET",
          path: "/groups/:id",
          requiresAuth: true,
          pathParams: ["id"],
        },
        {
          key: "tirelire-groups-invite",
          label: "Invite Member",
          method: "POST",
          path: "/groups/:id/invite",
          requiresAuth: true,
          pathParams: ["id"],
          bodyTemplate: { email: "member@example.com" },
        },
        {
          key: "tirelire-groups-distribute",
          label: "Distribute Round",
          method: "POST",
          path: "/groups/:id/distribute",
          requiresAuth: true,
          pathParams: ["id"],
        },
        {
          key: "tirelire-contribute",
          label: "Contribute to Group",
          method: "POST",
          path: "/contributions/group/:groupId/contribute",
          requiresAuth: true,
          pathParams: ["groupId"],
          bodyTemplate: { amount: 3000 },
        },
        {
          key: "tirelire-contributions-history",
          label: "Group Contributions",
          method: "GET",
          path: "/contributions/group/:groupId",
          requiresAuth: true,
          pathParams: ["groupId"],
        },
      ],
    },
    {
      name: "Payments",
      description: "Stripe powered payments.",
      endpoints: [
        {
          key: "tirelire-payment-create",
          label: "Create Payment Intent",
          method: "POST",
          path: "/contributions",
          requiresAuth: true,
          bodyTemplate: {
            groupId: "<groupId>",
            amount: 3000,
            currency: "mad",
          },
        },
        {
          key: "tirelire-payment-history",
          label: "My Payment History",
          method: "GET",
          path: "/contributions/history",
          requiresAuth: true,
        },
        {
          key: "tirelire-payment-group-history",
          label: "Group Payment History",
          method: "GET",
          path: "/contributions/group/:groupId/history",
          requiresAuth: true,
          pathParams: ["groupId"],
        },
      ],
    },
    {
      name: "KYC",
      description: "Identity verification endpoints.",
      endpoints: [
        {
          key: "tirelire-kyc-status",
          label: "Status",
          method: "GET",
          path: "/kyc/status",
          requiresAuth: true,
        },
        {
          key: "tirelire-kyc-upload",
          label: "Upload ID",
          method: "POST",
          path: "/kyc/upload",
          requiresAuth: true,
          multipart: true,
          fileFields: ["idImage"],
          bodyTemplate: {
            idImage: "binary",
          },
        },
        {
          key: "tirelire-kyc-verify",
          label: "Verify Face",
          method: "POST",
          path: "/kyc/verify-face",
          requiresAuth: true,
          multipart: true,
          fileFields: ["selfie"],
          bodyTemplate: {
            selfie: "binary",
          },
        },
        {
          key: "tirelire-kyc-review",
          label: "Review User",
          method: "POST",
          path: "/kyc/review/:userId",
          requiresAuth: true,
          pathParams: ["userId"],
          bodyTemplate: {
            status: "approved",
            notes: "Looks good",
          },
        },
        {
          key: "tirelire-kyc-pending",
          label: "Pending Reviews",
          method: "GET",
          path: "/kyc/pending",
          requiresAuth: true,
        },
        {
          key: "tirelire-kyc-history",
          label: "User History",
          method: "GET",
          path: "/kyc/history/:userId",
          requiresAuth: true,
          pathParams: ["userId"],
        },
      ],
    },
    {
      name: "Messaging",
      description: "Chat and notifications.",
      endpoints: [
        {
          key: "tirelire-messages-send",
          label: "Send Group Message",
          method: "POST",
          path: "/messages/group/:groupId",
          requiresAuth: true,
          multipart: true,
          pathParams: ["groupId"],
          fileFields: ["audio"],
          bodyTemplate: {
            content: "Salaam team!",
            audio: "binary",
          },
        },
        {
          key: "tirelire-messages-list",
          label: "List Group Messages",
          method: "GET",
          path: "/messages/group/:groupId",
          requiresAuth: true,
          pathParams: ["groupId"],
        },
        {
          key: "tirelire-notifications-list",
          label: "List Notifications",
          method: "GET",
          path: "/notifications",
          requiresAuth: true,
        },
        {
          key: "tirelire-notifications-read",
          label: "Mark Notification Read",
          method: "PATCH",
          path: "/notifications/:id/read",
          requiresAuth: true,
          pathParams: ["id"],
        },
      ],
    },
    {
      name: "Tickets",
      description: "Support center.",
      endpoints: [
        {
          key: "tirelire-ticket-create",
          label: "Create Ticket",
          method: "POST",
          path: "/tickets",
          requiresAuth: true,
          bodyTemplate: {
            subject: "Need help",
            description: "Payment not received",
          },
        },
        {
          key: "tirelire-ticket-list",
          label: "My Tickets",
          method: "GET",
          path: "/tickets",
          requiresAuth: true,
        },
        {
          key: "tirelire-ticket-detail",
          label: "Ticket Details",
          method: "GET",
          path: "/tickets/:ticketId",
          requiresAuth: true,
          pathParams: ["ticketId"],
        },
        {
          key: "tirelire-ticket-admin",
          label: "Admin Ticket List",
          method: "GET",
          path: "/tickets/admin",
          requiresAuth: true,
        },
        {
          key: "tirelire-ticket-respond",
          label: "Respond to Ticket",
          method: "PATCH",
          path: "/tickets/:ticketId/respond",
          requiresAuth: true,
          pathParams: ["ticketId"],
          bodyTemplate: {
            response: "Issue solved",
            status: "resolved",
          },
        },
      ],
    },
    {
      name: "Admin",
      description: "Control center endpoints.",
      endpoints: [
        {
          key: "tirelire-admin-message-user",
          label: "Message User",
          method: "POST",
          path: "/admin/users/:userId/message",
          requiresAuth: true,
          pathParams: ["userId"],
          bodyTemplate: {
            type: "info",
            content: "Welcome to Tirelire!",
          },
        },
        {
          key: "tirelire-admin-message-group",
          label: "Message Group",
          method: "POST",
          path: "/admin/groups/:groupId/message",
          requiresAuth: true,
          pathParams: ["groupId"],
          bodyTemplate: {
            type: "reminder",
            content: "Round closes Friday",
          },
        },
        {
          key: "tirelire-admin-users",
          label: "List Users (Admin)",
          method: "GET",
          path: "/admin/users",
          requiresAuth: true,
        },
        {
          key: "tirelire-admin-user-stats",
          label: "User Stats",
          method: "GET",
          path: "/admin/users/:userId/stats",
          requiresAuth: true,
          pathParams: ["userId"],
        },
      ],
    },
  ],
};

